// demo/components/shell/sports-rail.tsx
"use client"

import useSWR from "swr"
import Link from "next/link"
import { usePathname, useSearchParams } from "next/navigation"
import { Skeleton, Badge } from "@/components/ui/kit"
import { cn } from "@/lib/utils"
import { Trophy, Zap, Star, Gift, type LucideIcon } from "lucide-react"

interface SportRow {
  id: string
  slug: string
  name: string
  eventCount: number
  liveCount: number
}

const ICONS: Record<string, LucideIcon> = {
  football: Trophy,
}

export function SportsRail() {
  const { data, isLoading } = useSWR<{ sports: SportRow[] }>("/api/sports")
  const params = useSearchParams()
  const pathname = usePathname()
  const activeSport = params.get("sport") ?? "all"

  return (
    <aside className="flex w-full flex-col gap-4">
      <nav className="rounded-md border border-border bg-card">
        <div className="border-b border-border px-3 py-2 text-[11px] font-bold uppercase tracking-wider text-muted-foreground">
          Recommended
        </div>
        <div className="flex flex-col p-1">
          <RailLink href="/sport" icon={Star} label="Top offer" active={pathname === "/sport" && activeSport === "all"} />
          <RailLink href="/live" icon={Zap} label="Live now" />
          <RailLink href="/promotions" icon={Gift} label="Promotions" />
        </div>
      </nav>

      <nav className="rounded-md border border-border bg-card">
        <div className="border-b border-border px-3 py-2 text-[11px] font-bold uppercase tracking-wider text-muted-foreground">
          Sports
        </div>
        <div className="flex max-h-[520px] flex-col overflow-y-auto p-1">
          {isLoading &&
            Array.from({ length: 8 }).map((_, i) => <Skeleton key={i} className="mx-1 my-0.5 h-8" />)}
          {data?.sports.map((s) => {
            const Icon = ICONS[s.slug] ?? Trophy
            const active = pathname.startsWith("/sport") && activeSport === s.slug
            return (
              <Link
                key={s.id}
                href={`/sport?sport=${s.slug}`}
                className={cn(
                  "flex items-center gap-2 rounded px-2.5 py-1.5 text-sm transition-colors hover:bg-accent",
                  active ? "bg-accent font-semibold text-foreground" : "text-foreground/80",
                )}
              >
                <Icon className="size-4 shrink-0 text-muted-foreground" />
                <span className="flex-1 truncate">{s.name}</span>
                {s.liveCount > 0 && <Badge variant="live">{s.liveCount}</Badge>}
                <span className="text-[11px] tabular-nums text-muted-foreground">{s.eventCount}</span>
              </Link>
            )
          })}
        </div>
      </nav>
    </aside>
  )
}

function RailLink({ href, icon: Icon, label, active }: { href: string; icon: LucideIcon; label: string; active?: boolean }) {
  return (
    <Link
      href={href}
      className={cn(
        "flex items-center gap-2 rounded px-2.5 py-1.5 text-sm transition-colors hover:bg-accent",
        active ? "bg-accent font-semibold" : "text-foreground/80",
      )}
    >
      <Icon className="size-4 text-primary" />
      {label}
    </Link>
  )
}

// demo/src/components/SportsRail.vue
<template>
  <aside class="flex w-full flex-col gap-4 lg:block">
    <!-- Quick Links (Hidden on mobile to save vertical space, already in header) -->
    <nav class="hidden rounded-lg border border-border bg-card lg:block mb-4">
      <div class="border-b border-border px-3.5 py-2 text-[11px] font-bold uppercase tracking-wider text-slate-400">
        Recommended
      </div>
      <div class="flex flex-col p-1.5 gap-0.5">
        <router-link
          to="/sport"
          class="flex items-center gap-2.5 rounded px-2.5 py-2 text-xs font-semibold transition-colors hover:bg-accent"
          :class="!$route.query.sport || $route.query.sport === 'all' ? 'bg-accent text-white font-bold' : 'text-slate-300'"
        >
          <Star class="size-4 text-amber-400" />
          <span>Top offer</span>
        </router-link>

        <router-link
          to="/live"
          class="flex items-center gap-2.5 rounded px-2.5 py-2 text-xs font-semibold transition-colors hover:bg-accent text-slate-300"
        >
          <Zap class="size-4 text-amber-500" />
          <span>Live now</span>
        </router-link>

        <router-link
          to="/promotions"
          class="flex items-center gap-2.5 rounded px-2.5 py-2 text-xs font-semibold transition-colors hover:bg-accent text-slate-300"
        >
          <Gift class="size-4 text-blue-400" />
          <span>Promotions</span>
        </router-link>
      </div>
    </nav>

    <!-- Sports List -->
    <nav class="rounded-lg border border-border bg-card">
      <div class="hidden lg:flex items-center justify-between border-b border-border px-3.5 py-2">
        <span class="text-[11px] font-bold uppercase tracking-wider text-slate-400">Sports</span>
        <span class="rounded bg-blue-500/10 px-1.5 py-0.5 text-[10px] font-semibold text-blue-400">
          {{ sports.length }} Available
        </span>
      </div>

      <!-- Horizontal scroll on mobile, vertical list on desktop -->
      <div class="flex overflow-x-auto lg:max-h-[560px] lg:flex-col lg:overflow-y-auto p-1.5 gap-1.5 lg:gap-0.5 no-scrollbar">
        <div v-if="loading" class="flex lg:flex-col gap-2 p-2">
          <div v-for="i in 8" :key="i" class="h-8 w-24 lg:w-full shrink-0 animate-pulse rounded bg-accent/50"></div>
        </div>

        <router-link
          v-for="sport in sports"
          :key="sport.id"
          :to="{ path: '/sport', query: { sport: sport.slug } }"
          class="flex shrink-0 items-center gap-2 rounded px-3 lg:px-2.5 py-2 lg:py-1.5 text-xs transition-colors hover:bg-accent border lg:border-transparent border-border"
          :class="$route.query.sport === sport.slug ? 'bg-blue-600/20 font-bold text-blue-400 border-blue-500/30 lg:border-blue-500/30' : 'text-slate-300 bg-accent/30 lg:bg-transparent'"
        >
          <Trophy class="size-3.5 shrink-0 text-slate-400 hidden lg:block" />
          <span class="truncate whitespace-nowrap">{{ sport.name }}</span>

          <span v-if="sport.liveCount > 0" class="rounded bg-red-500/20 px-1.5 py-0.5 text-[10px] font-bold text-red-400">
            {{ sport.liveCount }}
          </span>
        </router-link>
      </div>
    </nav>
  </aside>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { Trophy, Star, Zap, Gift } from 'lucide-vue-next'
import { fetchSports, type SportItem } from '@/services/api'

const sports = ref<SportItem[]>([])
const loading = ref(true)

onMounted(async () => {
  sports.value = await fetchSports()
  loading.value = false
})
</script>
